name: CI

on:
    pull_request:
        branches:
            - main

jobs:
    php:
        name: PHP Quality Check
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php-version: [ '8.2', '8.1', '8.0', '7.4' ]

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    tools: composer

            -   name: Validate composer.json
                run: composer validate --strict

            -   name: Install dependencies
                run: composer install --no-interaction --prefer-dist

            -   name: PHP syntax check
                run: |
                    find src -type f -name "*.php" -print0 \
                    | xargs -0 -n 1 php -l

            -   name: Autoload check
                run: composer dump-autoload --optimize
